### ISSUE TITLE
[FEATURE REQUEST]  Easier Merlion Install on Azure Databricks

### ISSUE THREAD

**Issue by akhanafer** [salesforce/Merlion#56]
**Is your feature request related to a problem? Please describe.**

I've been trying to install Merlion and all the datasets on Azure Databricks for the past couple of days and it's proving to be very difficult. Here's what I've done so far:
1. Install Merlion on my cluster using pip. This was failing at first for some reason but started randomly working two days after my first try.
2. Install the dataset using the egg. I had to manually find and run `setup.py` to get the .egg file from the newly created `dist` folder. I then installed the datasets to my cluster using the egg. This was my first time using Python eggs so I'm not sure if this is standard procedure. It installed properly, but as soon as I try using any dataset I get an error saying `AssertionError: <some-long-path> does not contain dataset file.`

And now I don't know where to go from here. 
  
**Describe the solution you'd like**
It'd be nice for the dataset module to be pip-installable, just like the Merlion module is, without having to download the entire repo.

**Describe alternatives you've considered**
It seems like you really want to separate the Merlion module from the dataset module. I don't understand why exactly, but if you're not married to this idea, then I'd make everything installable with one pip-call. If you want to give the developer more control over whether or not to download the datasets, I think their are better ways to do it without having to download the entire repo then using pip 

**EDIT (January 6th 2022)**
It seems to be a bug. I'm able to use the anomaly detection datasets but not the forecasting datasets

**Comment by akhanafer** [comment]
I got it to work by doing the following:
1. Install the merlion module normally via `pip install salesforce-merlion`
2. Create a cluster on-init script that clones the Merlion repository and installs the ts_datasets module via `pip install -e Merlion/ts_datasets`
But this causes a huge increase in cluster initialization time so it'd be nice to have a more seamless installation process

**Comment by aadyotb** [comment]
@akhanafer we choose not to make `ts_datasets` installable directly from PyPI because we would like to package certain datasets binaries with the package, and have them stored in a single default root directory. We would prefer to avoid making the package itself too large by packaging actual dataset files within it. For this reason, we choose to have the users install the package in editable mode using `pip install -e ts_datasets/` after cloning the repo.

Note that you should not have to invoke `setup.py` to create an egg at any point in this process. I also suspect that the datasets which still worked when you installed in this manner were those which we download directly (e.g. NAB, UCR, M4). However for many of the multivariate forecasting datasets, we use the binary file included with the repo, and the root directory may be mis-specified if the package is not installed in editable mode, i.e. using the `-e` flag when calling `pip install -e ts_datasets/`.
