### ISSUE TITLE
SeattleTrail()[0] out of index

### ISSUE THREAD

**Issue by Frenz86** [salesforce/Merlion#6]
This dataset has some issue

**Comment by aadyotb** [comment]
Hi, can you please provide code/logs of how you set up your environment?

Note that the syntax `SeattleTrail()[0]` only works if you install `ts_datasets` in editable mode (i.e. with `pip install -e ts_datasets/`, rather than `pip install ts_datasets/`). Otherwise, you will have to specify the directory where the dataset can be found, e.g. `SeattleTrail(rootdir="data/multivariate/seattle_trail")[0]`.

**Comment by paulkass** [comment]
Feel free to reopen if any new information is presented
